tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Distributed revision control system
brew "git"
# Open source relational database management system
brew "mysql"
# Internet file retriever
brew "wget"
cask "docker"
cask "google-chrome"
cask "intellij-idea"
cask "istat-menus"
cask "iterm2"
cask "notion"
cask "oracle-jdk"
cask "postman"
cask "sequel-pro"
cask "shadowsocksx-ng"
cask "sourcetree"
cask "visual-studio-code"
